services:
  - type: web
    name: nhl-spring-app
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d7gmfu57vvec7386qpq0-a.oregon-postgres.render.com:5432/nhl_spring_app
      - key: DB_USERNAME
        value: admin
      - key: DB_PASSWORD
        value: IHlmwa6MAO4JAVTCJ06OCBAbFqER4NVW
      - key: PORT
        value: 10000
