spring:
  application:
    name: nhl-spring-app
  devtools:
    restart:
      enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nhldb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:5972}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: ${PORT:8081}
